### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: sun.misc.Cleaner

### ISSUE THREAD

**Issue by Hilal-Anwar** [HumbleUI/JWM#273]
Exception in thread "main" java.lang.NoClassDefFoundError: sun.misc.Cleaner
	at io.github.humbleui.skija.impl.Cleanable.<clinit>(Cleanable.java:19)
	at io.github.humbleui.skija.impl.Managed.<init>(Managed.java:20)
	at io.github.humbleui.skija.impl.Managed.<init>(Managed.java:10)
	at io.github.humbleui.skija.impl.RefCnt.<init>(RefCnt.java:7)
	at io.github.humbleui.skija.Typeface.<init>(Typeface.java:394)
	at io.github.humbleui.skija.FontMgr.matchFamilyStyleCharacter(FontMgr.java:109)
	at org.jwm.Example.<clinit>(Example.java:17)
I am getting this error when I built and ran the jar file.
I do not get this error when I run this on class path.
I am running the code in https://github.com/HumbleUI/JWM/tree/main/examples/dashboard/java
i am using java 21

**Comment by Hilal-Anwar** [comment]
You are right it was my mistake I was making jar using maven assembly plugin and the jar was not working properly.
On using spring plugin it is now working fine.
I have one more question on running it on class path the app icon is shown but it not shown when running the jar file.

![Screenshot 2023-10-05 125946](https://github.com/HumbleUI/JWM/assets/50636048/90a1667a-b2f8-47ab-83a1-01b5ce46d018)
![uiyut](https://github.com/HumbleUI/JWM/assets/50636048/937a8e28-3ee6-47c4-8b82-2b2642dda854)

On running with jar file.

![yteye](https://github.com/HumbleUI/JWM/assets/50636048/bbb9a7ee-ead2-4323-918b-2469c3b68423)

Path location.
![Screenshot 2023-10-05 130829](https://github.com/HumbleUI/JWM/assets/50636048/b5f89573-8b1b-4701-bc7d-90923d9a14be)

**Comment by tonsky** [comment]
Yeah, it requires an actual file on disk right now. If you package it as a jar, file will be compressed inside
